import Header from "@/components/Header";
import ReduxProvider from "@/components/providers/ReduxProvider";
import ThemeProvider from "@/components/providers/ThemeProvider";
import ThemeStateProvider from "@/components/providers/ThemeStateProvider";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "renovellib",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <ThemeProvider>
        <html lang="en">
          <ThemeStateProvider>
            {children}
          </ThemeStateProvider>
        </html>
      </ThemeProvider>
    </ReduxProvider>
  );
}
